apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
    - image: busybox:latest
      command:
        - sleep
        - "3600"
      imagePullPolicy: IfNotPresent
      name: busybox
      volumeMounts:
        - name: <nome do volume>
          mountPath: <diretorio dentro do container>
          readOnly: true
  restartPolicy: Always
  imagePullSecrets:
    - name: regcred
  volumes:
  - name: <nome do volume>
    secret:
      secretName: <nome do secret>
